# Generated by Django 5.1.3 on 2024-12-05 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_tache_etat_alter_tache_importance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='taches', to=settings.AUTH_USER_MODEL),
        ),
    ]
